Repository LSSTDESC/descqa, pull requests merged in 2018-08, with the labels that each got.

#136 Add uniqueness check in readiness test
  descqa/configs/readiness_protoDC2.yaml
  descqa/readiness_test.py
Labels: enhancement, validation: extragalactic

#139 Cosmetic and bug fixes for several tests; N(z) test using absolute ma…
  descqa/DeltaSigmaTest.py
  descqa/EllipticityDistribution.py
  descqa/NumberDensityVersusRedshift.py
  descqa/SizeStellarMassLuminosity.py
  descqa/configs/Nz_i_rest.yaml
Labels: enhancement

#140 First commit of Density test
  descqa/DensityVersusSkyPosition.py
  descqa/configs/DensityVersusExtinction.yaml
Labels: validation: post-DM

#147 add verification test for galaxies in truth catalog
  descqa/configs/truth_galaxy_verification_run1.1.yaml
  descqa/truth_galaxy_verification.py
Labels: verification: truth

#104 Img bkg tests
  descqa/ImgPkTest.py
  descqa/QuickBkgTest.py
  descqa/configs/image_background.yaml
  descqa/configs/image_power_spec.yaml
  descqa/utils.py
Labels: validation: post-DM

#150 update image psd test to show per-sensor result
  descqa/ImgPkTest.py
Labels: enhancement, validation: images
