Repository LSSTDESC/descqa, pull requests merged in 2020-12, with the labels that each got.

#197 Shear theory test update (ccl)
  descqa/shear_test.py
  setup.py
Labels: paper

#131 add new validation datasets to galaxy-shear correlation test (#128)
  descqa/DeltaSigmaTest.py
  descqa/configs/delta_sigma.yaml
  descqa/configs/delta_sigma_cfhtlens.yaml
  descqa/configs/delta_sigma_sdss_lowz.yaml
  descqa/configs/delta_sigma_sdss_main.yaml
  descqa/data/delta_sigma/SDSS_main.dat
  descqa/data/delta_sigma/cfhtlens_DS.dat
Labels: paper, validation data, validation: extragalactic

#132 velocity dispersion relationship of galaxy clusters
  descqa/configs/virial_scale.yaml
  descqa/virialscale_test.py
Labels: paper, validation: extragalactic

#87 Added tested bias validation test
  descqa/BiasVersusRedshift.py
  descqa/configs/bias_test.yaml
  run_master.sh
Labels: paper, validation: extragalactic
